#! /bin/sh

pgrep -x picom > /dev/null || picom &
pgrep -x conky > /dev/null || conky &
pgrep -x trayer > /dev/null || trayer --edge top --align right --widthtype pixel --width 137 --heighttype pixel --height 21 --transparent true --tint 0x431751 --alpha 0 --SetPartialStrut true &
pgrep -x volumeicon > /dev/null || volumeicon &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x nitrogen > /dev/null || nitrogen --restore &
pgrep -x udiskie > /dev/null || udiskie -s &

