#!/bin/bash

function send_notification() {
	volume=$(printf "%.0f\n" $(pamixer --get-volume-human))
	dunstify -a "changevolume" -u low -r 9991 -h int:value:"$volume" -i "volume-$1" "Volume: $volume%" -t 2000
}

case $1 in
up)
	pamixer -i 5
	send_notification $1
	;;
down)
	pamixer -d 5
	send_notification $1
	;;
mute)
	pamixer -t
	send_notification $1
	;;
esac
